### ISSUE TITLE
Refactor the way functions are exported

### ISSUE THREAD

**Issue by magopian** [JanitorTechnology/janitor#105]
Refs https://github.com/JanitorTechnology/janitor/pull/101#pullrequestreview-48833766

The idea is to replace all:

```js
function myFunc (/* ... */) {
  /* ... */
}

exports.myFunc = myFunc;
```

by:

```js
exports.myFunc = function (/* ... */) {
  /* ... */
}
```

**Comment by jankeromnes** [comment]
Thanks for opening this issue!

However, we try to keep the number of open issues low, so that finding issues is easier. We can do this by grouping small issues into bigger issues (e.g. the issues with "Wishlist" in their titles are a collection of multiple things we need to do, and markdown checkboxes are a nice tool to keep track of them), and by not filing an issue when we're about to open a separate pull request anyway. 🙂

**Comment by jankeromnes** [comment]
Closing this issue in favor of the pull request #106.
