### ISSUE TITLE
Burn bootstrap with fire 🔥

### ISSUE THREAD

**Issue by nt1m** [JanitorTechnology/janitor#113]
A few reasons I want to stop using bootstrap:
- Gives the burden of following the framework constraints
- Unnecessary bloat, we don't use most of the CSS provides
- Makes Janitor look like a lot of (mostly low-quality) websites

I'm planning to progressively do this:
Adding new pages that no longer use bootstrap (the new project/contributions pages), and progressively convert the old ones to stop using it (there would be settings + the homepage left to convert).

**Comment by nt1m** [comment]
To be clear, I plan to avoid any kind of framework as a replacement for bootstrap.

**Comment by jankeromnes** [comment]
Interesting idea! I'm all for removing Bootstrap as a dependency if we can find another way to have a fast, efficient, beautiful and responsive UI without it.

This new front-end should be as good as, or better, than the current front-end on the following aspects:
- **Fast**: The janitor.technology web app should be perceived as extremely fast to load.
- **Intuitive**: The front-end should not have any UX that can be perceived as surprising by any user. It should just work for everyone, regardless of their experience with other apps, or their pre-conceived expectations. Big, simple buttons, very short (or no) texts, and obvious status indicators (e.g. show when the app is waiting for the server, but don't force users to "freeze" with a too obvious "loading" icon). We should be useful without requiring *any* prior knowledge or documentation.
- **Efficient**: There should be almost no cognitive burden for our users to use our app. We shouldn't make them click several times, or follow convoluted UX flows, before giving them what they really want.
- Responsive: Our app should look and work great on small phones as well as on large screens.

If we meet all these criteria, and the new front-end is obviously better than the bootstrap one, then I'm OK for switching. 👍

**Comment by jankeromnes** [comment]
@arshdkhn1 kindly wrote down these suggestions while trying to use Janitor for the first time:

> 1. use some modern UI theme..

I believe this is in line with this very issue. You're now two people who dislike Bootstrap and want it gone. As the person who originally brought Bootstrap into this project, I would like to apologize that I didn't know any better. 😄

> 2. on the settings page, add save button.. If i am not wrong, name, username, and ssh key fields automatically saves once u enter text into it. Some user might not like this.

I agree! I've noticed that many people got confused by these (judging from the many times people submit these 4-5 times to be sure), and I've wanted to switch to much simpler and more obvious Save buttons. So 👍 on this!

> 3. Add social auth at least to make signin process easy

Agreed as well! This was requested by #46 and was already partly implemented in #80 (which I'll finish up and merge soon).

> 4. Gmail email wasn't verified.. 

Hm, actually many people complain about Janitor sign-in emails going to spam. I believe we should set up proper email headers so that they don't, and/or use MailChimp's (recently freed) API to send our emails, and also support "Sign in with GitHub" which will make emails less critical to this project.

**Comment by nt1m** [comment]
WIP I worked on during the internship: https://github.com/nt1m/janitor/tree/new-contributions-page

**Comment by nt1m** [comment]
Most of the stuff is ready, the biggest thing that's missing is CSS for icons and form feedback

**Comment by jankeromnes** [comment]
Exciting! Do you have a screenshot? I tried checking out your branch, but the result I got was a bit surprising:

![new-contributions](https://user-images.githubusercontent.com/599268/29912260-5b8d8fb6-8e31-11e7-9928-e54fbc391e69.png)

**Comment by arshdkhn1** [comment]
I will add some changes in next few days.. Is it cool if i work on all pages, not specifically contributions page?

**Comment by nt1m** [comment]
@arshdkhn1 Yep, please do :)

@jankeromnes Hmm, so the new design uses system fonts, so you might get different results. I should solve that. The footer link spacing needs to be fixed as well.

Other than that, the design currently doesn't take in account the case where you have no containers.

Here's a screenshot:

﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/1795135/29928406-2388388e-8e93-11e7-94a6-bf5b403f7ad7.png">

**Comment by jankeromnes** [comment]
:fire: :fire: :fire:
