### ISSUE TITLE
favicons support for all browsers

### ISSUE THREAD

**Issue by arshdkhn1** [JanitorTechnology/janitor#157]
I see favicons are not showing on mobile browsers. What are the browsers on which we want favicon to show?

**Comment by jankeromnes** [comment]
It's because Chrome (and maybe other browsers) don't support SVG favicons even though they're standard. Firefox does, so it works there. I'm pretty sad about using raster images when vector could be used, so there is currently no raster image on Janitor. But maybe this is childish and we should have some PNGs as well (making sure they have sufficient definition to look good on any giant screen)

**Comment by arshdkhn1** [comment]
I will address this issue in new design pages.

**Comment by jankeromnes** [comment]
Thanks! 👍

**Comment by arshdkhn1** [comment]
https://github.com/JanitorTechnology/janitor/pull/223
