### ISSUE TITLE
Add a Discourse for the Janitor community, with solutions to common issues

### ISSUE THREAD

**Issue by Coder206** [JanitorTechnology/janitor#26]
@jankeromnes I was thinking of having a page that has a list of solutions for issues that get encountered when using The Janitor, perhaps a wiki page?

**Comment by EtienneWan** [comment]
Gold idea. In fact, only README of each project gives quick start commands and general help, not related to the Janitor environment. This kind of help can't be added as a file in each project because those files don't have to be commited, so a wiki stays the best place for this kind of info.

I may suggest opening a Discourse, which is community oriented and some threads can be marked as wiki pages. (Or to have its own category on community.c9.Jo)

**Comment by jankeromnes** [comment]
:+1: for a wiki page! Maybe something like an F.A.Q? Thanks a lot for the suggestion! :)

**Comment by EtienneWan** [comment]
@jankeromnes To me, Discourse aims to replace a part of this combo.

IRC don't log the discussion by default and isn't topic oriented, which means if many people asks questions at the same time on IRC (which may probably happen for this project), you end up with a crowded-channel and can't do much of tracking questions.
Email is a good way to send some newsletter but I'm not sure many people use Mailing List (I don't use it, maybe because I'm too young).

GitHub issues and wiki are more modern (for sure!). But I would preserve issues for tracking bugs and features of the project itself, and GitHub wiki for instructions on how to contribute and build the project itself. I do think it's not a good idea to clutter issues and wiki with questions&tips about the "on top of the project".

In this case, Discourse may replace IRC and Email (including newsletter) and users can ask questions like "How to... on Janitor ?". The combo would become issues/wiki/Discourse.

P.S I'm basing this on my own experience with Discourse of Cloud9 (https://community.c9.io) on which I'm somewhat active. I don't use Mozilla discourse for the moment, so I can't tell if being active on multiple Discourse is a pain or not.

**Comment by notriddle** [comment]
Rust uses Discourse as a replacement for the old mailing list. I don't think the Rust mailing lists even exist any more (other than the archives). Rust does still have IRC, but Discourse could probably serve that role too.

Rust has the GitHub wiki turned off. What a wiki page would have is split between actual documentation (which goes in the repo), Discourse discussion, and the occasional RFC.

**Comment by jankeromnes** [comment]
Thanks a lot @EtienneWan and @notriddle for your opinion and examples! You've convinced me that Discourse is the way to go, so I've disabled this repo's Wiki (which was empty anyway), and I'll set up a Janitor Discourse soon.

**Comment by jankeromnes** [comment]
With @rcatolino we've set up a new Discourse instance at https://discourse.janitor.technology/ 🎉

If you have experience with Discourse and would like to help run it, please reach out! 😄

**Comment by EtienneWan** [comment]
I'm in ! Congrats for the setup ! :+1

**Comment by notriddle** [comment]
Can you turn "Log In With GitHub" on?

**Comment by jankeromnes** [comment]
It seems to be working! I wonder how well the OVH VPS 1 performance will be (I do find the Discourse interactivity just a little on the slow side, don't you?)

Also @EtienneWan and @notriddle I'll make you Discourse admins if you don't mind, because you seem to know how it works way better than I do :)

> Can you turn "Log In With GitHub" on?

Done! Although I find it a hassle that you need to sign into yet another place, so eventually I'd love use to make the Discourse use Janitor's transparent Single-Sign-On system (so that simply visiting https://discourse.janitor.technology automatically logs you in via https://janitor.technology, no extra step required).

**Comment by jankeromnes** [comment]
TODO:
- [ ] Replace separate Discourse authentication with Janitor's transparent Single-Sign-On (see [Discourse SSO docs](https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045))
- [ ] Add link to https://discourse.janitor.technology on https://janitor.technology once we feel the Discourse instance works well enough

**Comment by jankeromnes** [comment]
Regarding "solutions to common issues", I have posted this Discourse thread:

https://discourse.janitor.technology/t/troubleshooting-common-issues/

That way we can use it to describe common problems, how to address them, and then refer our users to it when they have the same issue (I've personally explain the Cloud9 SSH problem about 5 times in the past few days...)

**Comment by jankeromnes** [comment]
Well, let's close this now. Maybe one day we'll add transparent sign-in with Janitor, but GitHub is also pretty convenient.
