### ISSUE TITLE
Migrate to a SPA architecture

### ISSUE THREAD

**Issue by ishitatsuyuki** [JanitorTechnology/janitor#287]
Server templates are sometimes superior to SPA because there's less runtime scripts, but in general our resource delivery isn't really optimized.

I would recommend to migrate to [Nuxt.js](https://github.com/nuxt/nuxt.js/), which has the following benefits:

- HTML boilerplate can be automatically managed, such as favicons, JS/CSS resources, and SPA manifests.
- Write next-gen JavaScript without worry, because Babel and Webpack is fully integrated.
- It's a JS framework, so you can run the server side renderer and the API server in the same process.
  (SSR has other benefits, like inlining critical CSS)

That being said, migration costs time and maybe some people will have to learn Vue.js.

**Comment by jankeromnes** [comment]
Thanks a lot for this suggestion!

By SPA, do you mean "Single Page App"? It's my understanding that this is now considered a practice to avoid, because it doesn't work well with caching mechanisms like Service Workers. But I don't know for sure. @nt1m or @arshdkhn1, any thoughts on @ishitatsuyuki's suggestion?

In general, I feel like our web app performance is pretty good, but could definitely be improved. I'm not sure that our server-side templates are the most efficient mechanism, and I believe we could make progress on resource delivery (e.g. with a better Service Worker and/or an HTTP2 reverse proxy).

See also https://github.com/JanitorTechnology/janitor/projects/3, #4 and #16.

Additional details:
- I'm not too fond of heavy JS frameworks in general, especially if they need you to refactor your project in very idiosyncratic ways (e.g. React, Babel/Webpack, etc). Except if the framework shows exceptional benefits and yet the impact of using it remains quite small (i.e. the framework can easily be dropped if we discover that using it was a bad idea 1 year later).
- It's worth noting that we're in the process of shipping a [new design](https://janitor.technology/design/) that completely removes Bootstrap. I don't think @nt1m and @arshdkhn1 would be too keen on re-adding a new framework like Vue.js.
- Also, for our [JSON API](https://janitor.technology/reference/api/) we already use an in-house solution, [Self API](https://github.com/JanitorTechnology/selfapi), which is an extremely lightweight component that sits between our [API handlers](https://github.com/JanitorTechnology/janitor/tree/master/api) and the web server, and which allows you to add title, description and examples to your API handlers, and then generate HTML/Markdown documentation that's always up-to-date, and automatically run your handlers against their own examples to instantly get a great test coverage. Implementing is the best trade-off we found (other test libraries weren't as lightweight, and didn't have self-documentation and self-testing features from just a few meta-data on our handlers).

**Comment by ishitatsuyuki** [comment]
> It's my understanding that this is now considered a practice to avoid, because it doesn't work well with caching mechanisms like Service Workers.

You have some misunderstanding here. A single page app surely has some tradeoffs (such as big runtime script), but it works very well with service workers. In Nuxt.js, you can [do this](https://github.com/nuxt-community/pwa-module) with just several lines of config.

> I'm not too fond of heavy JS frameworks in general, especially if they need you to refactor your project in very idiosyncratic ways (e.g. React, Babel/Webpack, etc). Except if the framework shows exceptional benefits and yet the impact of using it remains quite small (i.e. the framework can easily be dropped if we discover that using it was a bad idea 1 year later).

Vue.js requires you to refactor your code to adopt a template syntax, but on the other hand you can write better code than raw AJAX. Webpack and Babel can be incrementally adopted, and there's not much cost for that.

> It's worth noting that we're in the process of shipping a new design that completely removes Bootstrap. I don't think nt1m and arshdkhn1 would be too keen on re-adding a new framework like Vue.js

Bootstrap is a CSS framework, and Vue.js is a isomorphic virtual DOM framework. Indeed there's migration costs to Vue.js, but we shouldn't be comparing different kind of things.

> Also, for our JSON API we already use an in-house solution, Self API

It sounds like it duplicates quite much of Swagger's functionality, which is the defacto standard of API designing. I don't think I have something else to say about this.

**Comment by arshdkhn1** [comment]
I also had thought of using some modern js framework like React.js or Vue.js but I guess I never shoot(maybe one time with Jan) it because I thought there is no great need of it in Janitor? I would let @jankeromnes and @nt1m take this decision.

We have worked on new design which uses templates and using new framework at this stage will not be best idea. Maybe we can put this into consideration for future releases. 

I like SPAs personally and If we were to pick any such frameworks then I would recommend [Next.js](https://zeit.co/blog/next) whose vue version is Nuxt.js because me and @nt1m have both worked with React, Redux etc. in past, so less migration time.

**Comment by notriddle** [comment]
I've got to side with @jankeromnes and @arshdkhn1 on this one. Users just don't spend enough time in the Janitor web app itself to justify shipping a big runtime script. We want users to bounce in briefly, and then quickly bounce out to the IDE (which already is a SPA).
