### ISSUE TITLE
Delete irill.janitor.technology container

### ISSUE THREAD

**Issue by beaufortfrancois** [JanitorTechnology/janitor#293]
I'd like to delete an old irill.janitor.technology container but I can't. I get an EMPTY_ERR http response after 2 minutes.

**Comment by jankeromnes** [comment]
Thanks for reporting this issue! This is because our IRILL server is down, unfortunately. Here is the error we see server-side when you attempt to delete an IRILL container:

```
[2018-03-07T19:33:10.596Z] [fail] destroying machine { Error: connect ETIMEDOUT 128.93.31.4:2376
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '128.93.31.4',
  port: 2376 }
```

However, we can delete containers manually from the DB (this won't actually delete the container at IRILL, but you'll no longer see it in your list, and when IRILL is back we'll be able to finish cleaning up). I'll try to do that soon.

**Comment by jankeromnes** [comment]
Update: I have manually removed your old container called "Chromium irill.janitor.technology".

**Comment by beaufortfrancois** [comment]
thanks!
