### ISSUE TITLE
Add Java to the Chromium container

### ISSUE THREAD

**Issue by phistuck** [JanitorTechnology/janitor#301]
The Developer Tools feature needs Java due to a [Closure Compiler](https://github.com/google/closure-compiler) dependency. It does not require it (it simply skips the step if it does not exist), but Closure Compiler warns about common mistakes, bad types and other stuff that are eventually needed to be checked after code changes.
(I assume Java is needed for the Android build as well anyway, in case one of the goals is to support Chromium for Android contributions)

Thank you!

**Comment by jankeromnes** [comment]
Thanks a lot for this suggestion!

Java 8 was already installed in all Janitor images by @Coder206 [20 days ago](https://github.com/JanitorTechnology/dockerfiles/commit/04f32a15c21685e0a54a3d4d457164af07e708c4).

This update should gradually make its way into all production images on Janitor. (It's not available on today's Chromium image, because to save space we often run [partial upgrades](https://github.com/JanitorTechnology/dockerfiles/blob/master/chromium/chromium-update.dockerfile), but I'll be sure to rebuild a Chromium image on top of the latest `ubuntu-dev` this week.)

Note that in the meantime, you can always run `sudo apt-get install default-jdk`, in any container.

**Comment by phistuck** [comment]
> Note that in the meantime, you can always run `sudo apt-get install default-jdk`, in any container.

Ah, that is what I was missing. I tried sudo apt-get install java and it found no package so quickly I just assumed it was not even reaching out to any server and so - tough luck. Great, I hope to try that later today.

Gracias. :)

**Comment by jankeromnes** [comment]
Nice! Thanks for verifying! 😄
