### ISSUE TITLE
Servo container needs new gstreamer dependencies

### ISSUE THREAD

**Issue by jdm** [JanitorTechnology/janitor#369]
There are new gstreamer packages that need to be installed for a successful servo build on linux now: https://github.com/servo/servo/blob/master/README.md#on-debian-based-linuxes

**Comment by jdm** [comment]
It appears that these commands are necessary, since xenial doesn't have recent-enough gstreamer dependencies: https://github.com/servo/servo/blob/3424a5c51f1acf2518c1473ce894fdf2117df91b/.travis.yml#L20-L22

**Comment by jankeromnes** [comment]
@jdm Thanks a lot for reporting this issue!

Would you mind opening a pull request against https://github.com/JanitorTechnology/dockerfiles/blob/master/servo/servo.dockerfile ?

> It appears that these commands are necessary, since xenial doesn't have recent-enough gstreamer dependencies: https://github.com/servo/servo/blob/3424a5c51f1acf2518c1473ce894fdf2117df91b/.travis.yml#L20-L22

This link mentions "trusty" (14.04) instead of "xenial" (16.04). Are you sure that simply updating the package list in [servo.dockerfile](https://github.com/JanitorTechnology/dockerfiles/blob/master/servo/servo.dockerfile) to what's listed in Servo's [README](https://github.com/servo/servo/blob/master/README.md#on-debian-based-linuxes) wouldn't be enough to get the right gstreamer?

**Comment by jankeromnes** [comment]
Hm, ok, I've updated Servo's package dependency list in https://github.com/JanitorTechnology/dockerfiles/pull/209 but that wasn't enough, because the CircleCI build failed with:

```
Requested 'gstreamer-1.0 >= 1.12' but version of GStreamer is 1.8.3
```

**Comment by jdm** [comment]
This should be addressed automatically by https://github.com/servo/servo/pull/21586 when it merges.
