### ISSUE TITLE
Firefox for Android support

### ISSUE THREAD

**Issue by jgmize** [JanitorTechnology/janitor#45]
Splitting this issue from https://github.com/JanitorTechnology/janitor/issues/24#issuecomment-285925528 for tracking purposes. Please [react](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) with 👍 if you like the split or feel free to close as dupe if you prefer to track exclusively with that issue.

**Comment by jankeromnes** [comment]
Thanks a lot @jgmize for taking the time to file this issue! However, as you guessed I've so far found it easier to track all projects from the single "roadmap-like" issue #24 (similarly to the other issues that start with "Wishlist: ").

The reason is that it's usually pretty easy to add a project (simply build a development-dockerfile, hook it up in Janitor, and voilà) and there is usually no need for more involved discussions than a "please add project X" message and a follow-up "project X is live!".

However, maybe you're right and Android-related work will take some dedicated discussions and more involved troubleshooting, in which case we should re-open this issue in order not to take the Wishlist issue too far off-topic.

Additionally, if you (or anyone else) would like to take on this issue personally, please assign yourself (or request to be assigned) and re-open the issue. We'd then be able to further discuss how to add a Janitor project.

Essentially:
- writing a Dockerfile for developers, with an SSH server, Cloud9 dependencies and a few other things
- then the image should be built and tested on a server
- and then a new project entry can be added to Janitor, pointing to the new Docker image
