### ISSUE TITLE
Trailing slash should not be needed when proxying to a hosted web app

### ISSUE THREAD

**Issue by bnjbvr** [JanitorTechnology/janitor#52]
STR
===

- Create a new Web project (e.g. Kresus)
- type the Janitor proxy URL without a trailing slash at the end: `https://janitor.technology/UNIQ_ID/9876`

Expected
===

This should hit `/` in the web app.

Observed
===

This returns a 404. The web app logs don't show any traffic to `/`.

If I correct the URL to use `https://janitor.technology/UNIQ_ID/9876/`, it works. I think it would be simpler for the users to allow the trailing slash or add it if it's not there. Jan tells me on IRC it might be an issue when the proxy and the web app are hosted on the same physical host.

**Comment by jankeromnes** [comment]
Thanks for reporting this problem! I marked it as `Good First Bug` because it can be done by making the [app.js proxy handler](https://github.com/JanitorTechnology/janitor/blob/4397f78cd50a276a9878dcdbb0f250946035c83c/join.js#L62) accept an optional path (i.e. by adding a `?` after `(\/.*)` in the regex), and by handling the case where there is no path, just like the [join.js proxy handler](https://github.com/JanitorTechnology/janitor/blob/4397f78cd50a276a9878dcdbb0f250946035c83c/join.js#L62-L76).

**Comment by jankeromnes** [comment]
Closing this issue because PR #188 removes the local proxy entirely, including this bug. Maybe it will get merged one day. 😋
