### ISSUE TITLE
Some HTTP methods don't get properly redirected in the service proxy

### ISSUE THREAD

**Issue by bnjbvr** [JanitorTechnology/janitor#54]
When using a service that's hosted in a container, e.g. a Web service, then the user can access the Web service, and all the requests get proxied through Janitor (which does a simple redirect). However, some methods aren't getting properly redirected: I have seen instances where `POST`, `PUT`, `DELETE` methods wouldn't ever reach the web service in the Docker instance.

**Comment by jankeromnes** [comment]
Thanks for filing this issue!

https://github.com/espadrine/sc/pull/60 should fix one proxy-related issue (request data disappearing because ScoutCamp processes it before the proxying handler does), and https://github.com/espadrine/sc/pull/45 should enable us to un-fork ScoutCamp and benefit from https://github.com/espadrine/sc/pull/60's fix.

Then, I'll investigate any further proxy issue: making sure that Kresus, Janitor, and the Cloud9 SDK all work through the Janitor proxy, and that `POST`, `PUT` and `DELETE` methods reach their intended destinations.

**Comment by jankeromnes** [comment]
@bnjbvr Hm, it looks like my words "partially fixes #54" in #62's first comment were interpreted by GitHub as "close the issue when this gets merged".

I do believe that Kresus' web preview now works over the proxy, but if you have time, could you please try your cURL commands again to verify that this issue is 100% fixed?

**Comment by bnjbvr** [comment]
Yes, I've retried and I can now create an account (POST), change a few properties (PUT) and delete the account (DELETE). Thanks for the great work here!

**Comment by jankeromnes** [comment]
Nice, thanks a lot for verifying!
