### ISSUE TITLE
VNC won't open

### ISSUE THREAD

**Issue by notriddle** [JanitorTechnology/janitor#63]
I deleted the container, added it back, and it still won't open.

**Comment by Coder206** [comment]
@notriddle Have you received an error message on your end?

**Comment by notriddle** [comment]
No error message. It just hangs.

**Comment by notriddle** [comment]
The project is Servo

**Comment by Coder206** [comment]
@notriddle Like this:
![page-shot-2017-5-6 novnc](https://cloud.githubusercontent.com/assets/7758155/25776990/f0b1819c-329c-11e7-9cfd-a89d3e2e8721.png)?

**Comment by notriddle** [comment]
Like that

**Comment by Coder206** [comment]
Curiously, the one above is a new container created tonight. I am still able to open an older container of Servo in VNC.

**Comment by Coder206** [comment]
I am receiving an error when navigating to https://moz1.janitor.technology/****************/8088/vnc.html

**Comment by jankeromnes** [comment]
Thanks a lot for opening this issue! I will have a look in the backend to see what's happening here.

**Comment by jankeromnes** [comment]
A few general notes:

- There is no need to hide container IDs from URLs. Janitor's OAuth2 proxy verifies container ownership (if you're not signed in to Janitor as the rightful owner of a container, accessing another user's URL will simply lead to a 404 error).
- Simply refreshing the noVNC page helps with many different issues (connection problems are often due to discrepancies between the noVNC resources loaded from cache and the WebSocket connection actually being established).

My current theory to explain this particular problem is that the latest Firefox, Servo, Thunderbird and Janitor images are based on a broken noVNC revision.

- The latest image update was on May 3, around 16:00 UTC.
- It looks like noVNC shows a similar quota-exceeded bug (in the JS Console)* on a Firefox image update from April 29, ~13:00 UTC, but not on an older update from March 23, ~10:00 UTC.

I didn't find a storage-quota-related bug in the [noVNC repository](https://github.com/novnc/noVNC/issues), but will trigger a new image update based on today's latest noVNC revision, and see if the problem is solved. If it's not, I'll file a noVNC bug, and maybe try to base another round of image updates on a last-known-good-revision of noVNC.

* `Failed to execute 'setItem' on 'Storage': Setting the value of 'https://moz1.janitor.technology/482bb14c21f81c5a/8088/<anon1>!raw' exceeded the quota.`

**Comment by jankeromnes** [comment]
- Updated "Janitor" project image from 10min ago, May 7 ~09:00 UTC still exhibits the noVNC-quota bug, but it appears to be a Chrome-only problem (Firefox Nightly displays noVNC just fine).

**Comment by jankeromnes** [comment]
This bug doesn't reproduce in older versions of noVNC, so I will bisect its offending commit in the coming days.

**Comment by DirectXMan12** [comment]
So, it looks like Babel is try to compile and store a very large JS file (it looks like one that's external to noVNC -- from your project).  We recently switched to using ES6 modules, and because module-loading support in the browsers is not quite there yet, we use a shim to compile the modules to SystemJS on the fly when using un-compiled noVNC.  The shim caches the compiled files for faster dev turnaround.

We expressly *do not* reccomend using the uncompiled form of noVNC in production, since running Babel in the browser is not recommended for production..  Instead, you should include a copy that's first been converted from ES6 modules to SystemJS, CommonJS, RequireJS, etc.  There's a tool in the `utils` directory (`utils/use_require.js`) which will do this for you.

**Comment by jankeromnes** [comment]
This problem was addressed upstream (by not crashing when the Local Storage quota is exceeded), and https://github.com/JanitorTechnology/dockerfiles/commit/3eff032de203967e74dd0e97e54b676b133e0b47 switches to a production noVNC build which shouldn't use Local Storage anymore.

This problem will stop reproducing on Janitor once all images are updated, and all noVNC buttons should also point to `vnc.html` again (instead of the current `vnc_auto.html`, which is not included in production builds, and was renamed to `vnc_lite.html` anyway).

**Comment by notriddle** [comment]
It works again. Thanks!

**Comment by jankeromnes** [comment]
You're welcome!

This bug was fixed by https://github.com/novnc/noVNC/commit/777df7c274222806b5d66412058cabf71f5d4ca7 (continue working when noVNC local storage storage is full) and by https://github.com/JanitorTechnology/janitor/commit/ae6e4eba2131aa0747778c60aa8466fae1bbb0bb (point Janitor to `./vnc.html` instead of `./vnc_auto.html` or `/vnc_lite.html`).

A further improvement was made in https://github.com/JanitorTechnology/dockerfiles/commit/3eff032de203967e74dd0e97e54b676b133e0b47 thanks to suggestions in the noVNC issue, and it will make Janitor switch to a much faster production build of noVNC that doesn't use Babel. This will go live when a new base image is built & deployed (in a few days I expect).
