### ISSUE TITLE
Use HTML 5 form error message

### ISSUE THREAD

**Issue by nt1m** [JanitorTechnology/janitor#71]
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Constraint_API%27s_element.setCustomValidity()

**Comment by jankeromnes** [comment]
Thanks for this suggestion! This could indeed replace our current [jQuery popover](https://github.com/JanitorTechnology/janitor/blob/09a9be026049d184dd4187a6bfe86a9949bf316d/static/js/janitor.js#L128-L136).

**Comment by magopian** [comment]
Just so I get the context, why not "simply" display the error message in the page itself (usually that's done just above or just below the form input)? Is it because it's visually more appealing?

**Comment by jankeromnes** [comment]
Thanks for your question and suggestion! 😄

I think that there is no particular reason. We currently display `form` feedback after an API call (e.g. "Successfully deployed to 3 containers", or "Error: Signing in currently requires an invitation", etc) as a jQuery popover, and Tim was proposing to use the more standard `element.setCustomValidity()` instead.

We could very well show API feedback messages inline (before or after a form or input), but we'd just need to figure out the right UX for this (e.g. how to make sure all messages are displayed somewhere that makes sense? Can messages be "dismissed"? Can page reflows resulting from adding/removing an inline feedback message break stuff, e.g. on mobile? etc).

**Comment by nt1m** [comment]
@magopian Using `element.setCustomValidity()` saves a bit  of code, and is a standard way to do things as welll :)

**Comment by jankeromnes** [comment]
@magopian I provisionally assigned you to this issue, because you mentioned on IRC that you might be interested in tackling this. Please let me know if you have any question about how the current UI works!

I can already give you a few code pointers:
- The current form feedback elements are added by [this function](https://github.com/JanitorTechnology/janitor/blob/932f089eb3f4ac324b1860d6d1c544f532447428/static/js/janitor.js#L189-L215). It consists of hidden bootstrap [glyphicons](http://getbootstrap.com/components/#glyphicons) (specifically, a green checkmark and a red X), which each become visible when the right [CSS class](https://github.com/JanitorTechnology/janitor/blob/932f089eb3f4ac324b1860d6d1c544f532447428/static/css/janitor.css#L238-L244) is set in the containing `<form>` element.
- This feedback element also has a jQuery "popover" element, which shows when the feedback element is focused (and clicking anywhere in the page changes the focus so the message will disappear again).
