### ISSUE TITLE
Skip going to c9.io to access containers

### ISSUE THREAD

**Issue by magopian** [JanitorTechnology/janitor#92]
Once https://github.com/JanitorTechnology/janitor/projects/2#card-3182746 is done, we should be able to replace the "Edit in Cloud9" button in the screenshot below with a "connect to your container" or something along those lines, and skip connecting to Cloud9.

<img width="865" alt="screen shot 2017-07-03 at 19 06 58" src="https://user-images.githubusercontent.com/167767/27802266-ec53fe1e-6022-11e7-9609-a6ffd1499ee3.png">

The link has this form: `https://moz1.janitor.technology/<container>/8089/ide.html` (the container is the same as the one in the `VNC` button).

**Comment by jankeromnes** [comment]
I did some research for https://github.com/JanitorTechnology/janitor/projects/2#card-3182746, which suggests passing `:container` and `:port` via the hostname instead of via the URL (still works when proxied apps use absolute URLs), so something like `https://8080.abcdef123456.moz1.janitor.technology/` instead of `https://moz1.janitor.technology/abcdef123456/8080/` (or even `https://moz1.janitor.technology/?container=abcdef123456&port=8080`, which is supported too).

The problem with the hostname solution is that in order to continue serving HTTPS, we need to generate many different LetsEncrypt certificates (because they don't support wildcard certificates for domains like `*.*.moz1.janitor.technology`, forcing us to generate certificates that contain all supported hostnames explicitely).

We can make the proxy server handle multiple hostnames with an SNI handler, and generate LetsEncrypt certificates on-demand, but we risk hitting their [rate limits](https://letsencrypt.org/docs/rate-limits/) of 20 certificates per week.

Instead of generating all certificates using a single Janitor account (which would limit the entire service to 20 new containers per month), we could generate certificates using the users' email addresses. The problem with that is we start eating into their rate limits (if they create 20 containers on Janitor, they can't use LetsEncrypt for an entire week), and they might also receive confusing expiry notices (which is unnecessary since Janitor will re-generate certificates on-demand before they expire).
