### ISSUE TITLE
Add live-reloading to the project

### ISSUE THREAD

**Issue by magopian** [JanitorTechnology/janitor#95]
It would be very convenient to have the app restart automatically whenever some files change. I believe there's many different solutions that would do that out there.

**Comment by jankeromnes** [comment]
Very cool suggestion! Looks like many developers expect to have this nowadays, because you're not the first to request this feature 😃. See also https://github.com/JanitorTechnology/janitor/projects/2#card-3209302.

Also, @nt1m might be interested in addressing this (except if you've already started @magopian?)

**Comment by magopian** [comment]
Haven't started, not yet ;)

**Comment by jankeromnes** [comment]
This issue is being tackled in pull request #103, so I'm closing it in order to keep the list of open issues small and readable.
